name: Build & Run Test - Clang

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  C_COMPILER: clang
  CPP_COMPILER: clang++

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: > 
        cmake .. 
        -DCMAKE_CXX_COMPILER=$${{env.CPP_COMPILER}}
        -DCMAKE_C_COMPILER=${{env.C_COMPILER}}
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./main

